<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmrdpfl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmrdpfl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYmrdpfl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYmrdpfl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYmrdpfl\appProdProjectContainer([
    'container.build_hash' => 'Ymrdpfl',
    'container.build_id' => 'd3fc01ca',
    'container.build_time' => 1638554139,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmrdpfl');
